<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LAPORAN</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #2c3e50;
        }
        .header p {
            margin: 5px 0 0;
            color: #7f8c8d;
        }
        .stats-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            gap: 20px;
        }
        .stat-card {
            flex: 1 1 200px;
            min-width: 200px;
            background: #f9f9f9;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            text-align: center;
        }
        .stat-value {
            font-size: 32px;
            font-weight: bold;
            color: #2c3e50;
            margin: 10px 0;
        }
        .stat-caption {
            color: #7f8c8d;
            font-size: 14px;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #95a5a6;
            border-top: 2px solid #eee;
            padding-top: 20px;
        }
        @media print {
            body {
                padding: 0;
            }
            .stat-card {
                box-shadow: none;
                border: 1px solid #ddd;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>PT AGUS JAYA KARDUS</h1>
        <p>Laporan Bulan: <?php echo date('F j, Y'); ?></p>
    </div>

    <div class="stats-container">
        <div class="stat-card">
            <div class="stat-value">{{ $products }}</div>
            <div class="stat-caption">Total Produk</div>
        </div>
        
        <div class="stat-card">
            <div class="stat-value">{{ $categories }}</div>
            <div class="stat-caption">Total Kategori</div>
        </div>
        
        <div class="stat-card">
            <div class="stat-value">{{ $customers }}</div>
            <div class="stat-caption">Total Pembeli</div>
        </div>
        
        <div class="stat-card">
            <div class="stat-value">{{ $collectors }}</div>
            <div class="stat-caption">Total Pengepul</div>
        </div>
        
        <div class="stat-card">
            <div class="stat-value">{{ $transactions }}</div>
            <div class="stat-caption">Total Transaksi</div>
        </div>
        
        <div class="stat-card">
            <div class="stat-value">{{ $requestOrders }}</div>
            <div class="stat-caption">Total Permintaan</div>
        </div>
        
        <div class="stat-card">
            <div class="stat-value">Rp.{{ $totalIncome }}</div>
            <div class="stat-caption">Total Pemasukan</div>
        </div>
        
        <div class="stat-card">
            <div class="stat-value">Rp.{{ $totalOutcome }}</div>
            <div class="stat-caption">Total Pengeluaran</div>
        </div>
    </div>

    <div class="footer">
        <p>This report was automatically generated by the Document Management System</p>
    </div>

    <script>
        // Auto-print the page when loaded (optional)
        window.onload = function() {
            setTimeout(function() {
                window.print();
            }, 500);
        };
    </script>
</body>
</html>